- defaults:
    link:
      create: true
      relink: true

- create:
  - ~/bin
  - ~/.vim
  - ~/.bashrc.better.d

- clean: ['~', '~/.config']

- link:
    ~/.dircolors:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.tigrc:
    ~/.tmux.conf:
    ~/.tmux.theme.conf:
    ~/.vimrc.bundles:
    ~/.vimrc:
    ~/.bashrc.better:
    ~/bin/:
      path: bin/*
      glob: true
    ~/bin/icdiff: external/icdiff/icdiff
    ~/bin/git-icdiff: external/icdiff/git-icdiff

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
