- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.vimrc:

- create:
  - ~/bin

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
