- defaults:
    link:
      create: true
      relink: true

- create:
  - ~/bin
  - ~/.vim
  - ~/.tmux
  - ~/.tmux/plugins
  - ~/.bashrc.better.d

- clean: ['~', '~/.config']

- shell:
  - [git submodule sync && git submodule update --init --recursive, Installing submodules]

- link:
    ~/.dircolors:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.tigrc:
    ~/.tmux.conf:
    ~/.tmux.theme.conf:
    ~/.tmux/plugins/tpm: external/tpm
    ~/.vimrc.bundles:
    ~/.vimrc:
    ~/.bask: external/bask
    ~/.bash-git-prompt: external/bash-git-prompt
    ~/.bashrc.better:
    ~/bin/:
      path: bin/*
      glob: true
    ~/bin/icdiff: external/icdiff/icdiff
    ~/bin/git-icdiff: external/icdiff/git-icdiff
    ~/bin/fpp: external/PathPicker/fpp
    ~/bin/kubectx: external/kubectx/kubectx
    ~/bin/kubens: external/kubectx/kubens
    ~/.bashrc.better.d/:
      path: bashrc.better.d/*
      glob: true
    ~/.git-prompt-colors.sh:
    ~/.fzf: external/fzf

- shell:
  - [ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim, Installing vim plugin manager ]
  - [ ~/.fzf/install, Installing fzf ]
