#!/usr/bin/env bash

set -e

CONFIG=".install.conf.yaml"
DOTBOT_DIR=".dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
pushd "${DOTBOT_DIR}" > /dev/null
git submodule sync --quiet --recursive
popd > /dev/null
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# This is executed outside of dotbot due to needing interactive session
vim +PlugClean +PlugInstall +PlugUpdate +qall --not-a-term
